import { useEffect, useState } from 'react';
import { Gauge, Target } from 'lucide-react';

type Activity = { quantity: number; status: 'pending' | 'executed' | 'failed'; date?: string };
const KEY = 'founder-os-daily-productivity';

export function ProductivityGauge() {
  const [activities, setActivities] = useState<Activity[]>([]);
  useEffect(() => { const load = () => { try { setActivities(JSON.parse(localStorage.getItem(KEY) || '[]')); } catch { setActivities([]); } }; load(); window.addEventListener('storage', load); window.addEventListener('founder-productivity-updated', load); return () => { window.removeEventListener('storage', load); window.removeEventListener('founder-productivity-updated', load); }; }, []);
  const today = new Date().toISOString().slice(0, 10); const current = activities.filter((item) => !item.date || item.date === today); const done = current.filter((item) => item.status === 'executed').reduce((sum, item) => sum + item.quantity, 0); const failed = current.filter((item) => item.status === 'failed').reduce((sum, item) => sum + item.quantity, 0); const pending = current.filter((item) => item.status === 'pending').reduce((sum, item) => sum + item.quantity, 0); const score = done + failed ? Math.round(done / (done + failed) * 100) : 0;
  return <section className="rounded-2xl border border-[#00C9FF35] bg-[#07101a]/80 p-5 shadow-[0_0_24px_#00c9ff0a]"><div className="mb-4 flex items-center gap-2"><Gauge className="h-5 w-5 text-primary" /><div><p className="text-[10px] uppercase tracking-[.18em] text-primary">PAINEL DE PERFORMANCE</p><h2 className="text-lg font-semibold">Execução do dia</h2></div></div><div className="grid gap-5 lg:grid-cols-[280px_1fr]"><div className="flex flex-col items-center justify-center rounded-xl border border-white/[0.07] bg-black/20 p-4"><div className="relative h-48 w-48 rounded-full p-4" style={{ background: `conic-gradient(from 270deg, #10B981 ${score * 1.8}deg, #F97316 ${score * 1.8}deg 180deg, #1e293b 180deg 360deg)` }}><div className="flex h-full w-full flex-col items-center justify-center rounded-full bg-[#07101a]"><strong className="text-5xl">{score}%</strong><span className="text-[10px] uppercase tracking-wider text-muted-foreground">consistência</span></div></div><p className="mt-2 text-[10px] text-muted-foreground">Feitas x não realizadas</p></div><div className="productivity-performance-stats grid content-center gap-3 sm:grid-cols-3"><Stat icon={<Target className="h-4 w-4" />} label="Executadas" value={done} color="#10B981" /><Stat icon={<Target className="h-4 w-4" />} label="Pendentes" value={pending} color="#F59E0B" /><Stat icon={<Target className="h-4 w-4" />} label="Não realizadas" value={failed} color="#F97316" /></div></div></section>;
}
function Stat({ icon, label, value, color }: { icon: React.ReactNode; label: string; value: number; color: string }) { return <div className="rounded-xl border p-4" style={{ borderColor: `${color}55`, background: `${color}0d` }}><div className="flex items-center gap-2" style={{ color }}>{icon}<strong className="text-2xl">{value}</strong></div><p className="mt-1 text-xs text-muted-foreground">{label}</p></div>; }
