import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, ArrowRight, BarChart3, ShieldAlert } from 'lucide-react';
import { Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { useAppStore } from '@/store/useAppStore';
import { RiskBlock } from '@/components/overview/RiskBlock';

export default function AlertRisk() {
  const { risks, nextActions, transactions } = useAppStore();
  const accountBalance = transactions.filter(t => t.type === 'income').reduce((s, t) => s + t.amount, 0) - transactions.filter(t => t.type === 'expense').reduce((s, t) => s + t.amount, 0);
  const [floor, setFloor] = useState(() => Number(localStorage.getItem('founder-os-psychological-floor') || 1000));
  const below = accountBalance < floor;
  const high = risks.filter(r => r.severity === 'high').length;
  const medium = risks.filter(r => r.severity === 'medium').length;
  const low = risks.filter(r => r.severity === 'low').length;
  const open = nextActions.filter(a => !a.done).slice(0, 5);
  const riskIndex = risks.length ? Math.round(risks.reduce((s, r) => s + (r.score ?? (r.severity === 'high' ? 80 : r.severity === 'medium' ? 52 : 24)), 0) / risks.length) : 0;
  const evolution = [82, 76, 71, 74, 66, 62, riskIndex].map((value, i) => ({ day: `${20 + i}/07`, value }));
  const saveFloor = (value: number) => { setFloor(value); localStorage.setItem('founder-os-psychological-floor', String(value)); };
  return <div className="max-w-[1600px] space-y-6">
    <header className="rounded-xl border border-red-500/30 bg-gradient-to-r from-[#1a0a0d] via-card to-[#120e0e] p-6"><div className="flex flex-wrap items-center justify-between gap-5"><div><div className="flex items-center gap-2 text-red-400"><AlertTriangle className="h-5 w-5" /><span className="text-xs font-semibold uppercase tracking-[.2em]">Centro de Risco</span></div><h1 className="mt-2 text-3xl font-bold">Sua trajetoria. Seus riscos. Suas decisoes.</h1></div><div className="alert-summary-grid grid grid-cols-2 gap-2 sm:grid-cols-4"><Stat label="Indice geral" value={`${riskIndex}%`} color="#EF4444" /><Stat label="Prioridade" value={risks.find(r => r.severity === 'high')?.category || 'Estavel'} color="#F97316" /><Stat label="Impacto" value={high ? 'Muito alto' : 'Moderado'} color="#EF4444" /><Stat label="Acoes abertas" value={open.length} color="#00C9FF" /></div></div></header>
    <div className="grid gap-4 xl:grid-cols-3 xl:items-stretch">
      <div><section className={`h-full rounded-xl border p-5 ${below ? 'border-red-500/70 bg-red-950/20' : 'border-emerald-500/40 bg-emerald-950/10'}`}><AlertTriangle className={`mb-3 h-8 w-8 ${below ? 'text-red-400' : 'text-emerald-400'}`} /><h2 className={`font-bold uppercase tracking-wide ${below ? 'text-red-300' : 'text-emerald-300'}`}>{below ? 'Alerta de piso psicologico' : 'Piso psicologico protegido'}</h2><p className="mt-2 text-sm text-foreground/80">{below ? <>Seu caixa disponivel caiu abaixo do piso definido de <strong className="text-red-300">{formatCurrency(floor)}</strong>. Hora de executar o plano de recuperacao.</> : <>Seu caixa esta acima do piso psicologico definido de <strong className="text-emerald-300">{formatCurrency(floor)}</strong>.</>}</p><div className="mt-4 flex flex-wrap items-center gap-4"><span className={`text-2xl font-bold ${below ? 'text-red-400' : 'text-emerald-400'}`}>{formatCurrency(accountBalance)}</span><span className="text-xs text-muted-foreground">Piso: {formatCurrency(floor)}</span>{below && <span className="text-xs text-red-300">Faltam {formatCurrency(Math.max(0, floor - accountBalance))}</span>}</div></section></div>
      <FloorEditor value={floor} onChange={saveFloor} />
      <FloorRiskChart balance={accountBalance} floor={floor} />
    </div>
    <RiskBlock />
    <div className="grid gap-4 xl:grid-cols-4"><Panel title="Panorama dos riscos"><div className="flex items-center gap-5"><div className="relative h-28 w-28 rounded-full p-2" style={{ background: `conic-gradient(#EF4444 ${high * 100 / Math.max(risks.length, 1)}%, #F59E0B 0 ${((high + medium) * 100 / Math.max(risks.length, 1))}%, #10B981 0)` }}><div className="flex h-full w-full flex-col items-center justify-center rounded-full bg-[#100d10]"><strong className="text-2xl">{risks.length}</strong><span className="text-[9px] uppercase text-muted-foreground">riscos</span></div></div><div className="space-y-3 text-xs"><Legend color="#EF4444" label="Criticos" value={high} /><Legend color="#F59E0B" label="Atencao" value={medium} /><Legend color="#10B981" label="Baixos" value={low} /></div></div></Panel><Panel title="Evolucao dos riscos (7 dias)"><div className="h-40"><ResponsiveContainer width="100%" height="100%"><LineChart data={evolution}><XAxis dataKey="day" tick={{ fill: '#64748b', fontSize: 9 }} /><YAxis domain={[0, 100]} hide /><Tooltip contentStyle={{ background: '#100d10', border: '1px solid #ef444455' }} /><Line dataKey="value" stroke="#EF4444" strokeWidth={2} dot={{ r: 2, fill: '#100d10', stroke: '#EF4444' }} /></LineChart></ResponsiveContainer></div></Panel><Panel title="Proximas acoes criticas"><div className="space-y-2">{open.map(a => <div key={a.id} className="flex items-center gap-2 rounded-md border border-red-500/20 bg-red-950/10 p-2.5 text-xs"><ShieldAlert className="h-4 w-4 text-red-400" /><span className="flex-1">{a.text}</span><ArrowRight className="h-3 w-3 text-red-400" /></div>)}</div></Panel><Panel title="Impacto provavel (60 dias)"><div className="space-y-2">{['Liberdade financeira', 'Oportunidades', 'Saude e energia', 'Sistemas e escala'].map((item, i) => <div key={item} className="flex items-center gap-3 rounded-md border border-red-500/20 bg-red-950/10 p-2.5"><BarChart3 className="h-4 w-4 text-red-400" /><div><p className="text-xs">{item}</p><p className="text-[10px] font-semibold uppercase text-red-400">{i === 0 ? 'Muito alto' : 'Alto'}</p></div></div>)}</div></Panel></div>
  </div>;
}

function formatCurrency(value: number) { return value.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' }); }
function FloorEditor({ value, onChange }: { value: number; onChange: (value: number) => void }) {
  const [draft, setDraft] = useState(formatCurrency(value));
  useEffect(() => setDraft(formatCurrency(value)), [value]);
  const parseDraft = (raw: string) => {
    const normalized = raw.replace(/[^0-9,.-]/g, '').replace(/\./g, '').replace(',', '.');
    return Math.max(0, Number(normalized) || 0);
  };
  const updateDraft = (raw: string) => {
    setDraft(raw);
    if (raw.trim()) onChange(parseDraft(raw));
  };
  const commit = () => {
    const parsed = parseDraft(draft);
    onChange(parsed);
    setDraft(formatCurrency(parsed));
  };
  return <section className="h-full rounded-xl border border-amber-500/25 bg-amber-950/10 p-5"><p className="text-xs font-semibold uppercase tracking-wider text-amber-300">Piso psicologico</p><p className="mt-2 text-[11px] text-muted-foreground">Defina o limite que dispara o alerta financeiro.</p><label className="mt-5 flex items-center gap-2"><span className="text-sm text-muted-foreground">R$</span><input type="text" inputMode="decimal" value={draft} onChange={e => updateDraft(e.target.value)} onBlur={commit} onKeyDown={e => { if (e.key === 'Enter') { e.preventDefault(); commit(); e.currentTarget.blur(); } }} className="w-full rounded-md border border-amber-400/40 bg-background px-3 py-2 text-right text-2xl font-semibold text-amber-300 outline-none focus:border-amber-300" /></label></section>;
}
function FloorRiskChart({ balance, floor }: { balance: number; floor: number }) { const difference = balance - floor; const differencePercent = floor > 0 ? Math.round(difference / floor * 100) : 0; const ringPercent = Math.min(100, Math.abs(differencePercent)); const critical = difference < 0; const near = difference >= 0 && differencePercent < 25; const color = critical ? '#EF4444' : near ? '#F59E0B' : '#10B981'; const label = critical ? 'Abaixo do piso' : near ? 'Proximo do piso' : 'Piso protegido'; return <section className="h-full rounded-xl border border-white/10 bg-[#0d1118] p-5"><div className="flex items-center gap-2"><span className={`floor-risk-light ${critical ? 'floor-risk-alert' : ''}`} style={{ background: color, boxShadow: `0 0 10px ${color}` }} /><BarChart3 className="h-4 w-4" style={{ color }} /><h2 className="text-sm font-semibold">Grafico de alerta do piso</h2></div><p className="mt-2 text-xs text-muted-foreground">Monitoramento da diferenca entre o saldo e o piso psicologico.</p><span className="mt-4 inline-block rounded-full border px-3 py-1 text-xs font-semibold" style={{ color, borderColor: `${color}66` }}>{label}</span><div className="mt-5 flex items-center gap-5"><div className="flex h-32 w-32 shrink-0 items-center justify-center rounded-full p-2" style={{ background: `conic-gradient(${color} ${ringPercent}%, #1e293b ${ringPercent}% 100%)` }}><div className="flex h-full w-full flex-col items-center justify-center rounded-full bg-[#0d1118]"><strong className="text-2xl" style={{ color }}>{differencePercent > 0 ? '+' : ''}{differencePercent}%</strong><span className="text-[10px] uppercase text-muted-foreground">diferenca</span></div></div><div className="min-w-0 flex-1"><p className="text-xs text-muted-foreground">Diferenca atual</p><p className="text-2xl font-bold" style={{ color }}>{difference > 0 ? '+' : ''}{formatCurrency(difference)}</p><p className="mt-3 text-xs text-muted-foreground">Saldo: {formatCurrency(balance)} · Piso: {formatCurrency(floor)}</p><div className="mt-3 h-3 overflow-hidden rounded-full bg-slate-900"><div className="h-full rounded-full" style={{ width: `${ringPercent}%`, background: color }} /></div></div></div></section>; }
function Stat({ label, value, color }: { label: string; value: string | number; color: string }) { return <div className="rounded-md border border-white/10 bg-black/20 px-3 py-2"><p className="text-[9px] uppercase text-muted-foreground">{label}</p><p className="mt-1 text-lg font-bold" style={{ color }}>{value}</p></div>; }
function Legend({ color, label, value }: { color: string; label: string; value: number }) { return <div className="flex items-center gap-2"><i className="h-2.5 w-2.5 rounded-full" style={{ background: color }} />{label}<strong className="ml-3" style={{ color }}>{value}</strong></div>; }
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-xl border border-red-500/20 bg-[#100d10] p-4"><h2 className="mb-4 text-xs font-semibold uppercase tracking-wider">{title}</h2>{children}</section>; }
