import { useEffect, useMemo, useState } from 'react';
import { Activity, BarChart3, BriefcaseBusiness, CircleDollarSign, ListChecks, ShieldAlert, Target } from 'lucide-react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { useAppStore } from '@/store/useAppStore';

const chartTip = { background: '#10141d', border: '1px solid #334155', borderRadius: 10 };
const money = (value: number) => value.toLocaleString('pt-BR', { style: 'currency', currency: 'BRL', maximumFractionDigits: 0 });
const colors = ['#00C9FF', '#8B5CF6', '#10B981', '#F97316', '#EF4444'];

export default function Analysis() {
  const { modules, weeklyData, transactions, habits, risks, lifeAreas } = useAppStore();
  const [productivity, setProductivity] = useState<{ status: string; quantity: number; date: string }[]>([]);
  useEffect(() => {
    const load = () => { try { setProductivity(JSON.parse(localStorage.getItem('founder-os-daily-productivity') || '[]')); } catch { setProductivity([]); } };
    load(); window.addEventListener('founder-productivity-updated', load); window.addEventListener('storage', load);
    return () => { window.removeEventListener('founder-productivity-updated', load); window.removeEventListener('storage', load); };
  }, []);
  const projects = modules.filter((item) => item.type === 'project');
  const accounts = modules.filter((item) => item.type === 'financial_account');
  const income = transactions.filter((item) => item.type === 'income').reduce((sum, item) => sum + item.amount, 0);
  const expenses = transactions.filter((item) => item.type === 'expense').reduce((sum, item) => sum + item.amount, 0);
  const balance = accounts.reduce((sum, account) => sum + (account.balance || 0), 0) || income - expenses;
  const habitChecks = habits.flatMap((habit) => Object.values(habit.checks || {}));
  const habitScore = habitChecks.length ? Math.round(habitChecks.reduce((sum, status) => sum + (status === 'done' ? 1 : status === 'partial' ? .5 : 0), 0) / habitChecks.length * 100) : 0;
  const done = productivity.filter((item) => item.status === 'executed').reduce((sum, item) => sum + item.quantity, 0);
  const failed = productivity.filter((item) => item.status === 'failed').reduce((sum, item) => sum + item.quantity, 0);
  const productivityScore = done + failed ? Math.round(done / (done + failed) * 100) : 0;
  const riskScore = risks.length ? Math.round(risks.reduce((sum, risk) => sum + (risk.score || (risk.severity === 'high' ? 80 : risk.severity === 'medium' ? 50 : 20)), 0) / risks.length) : 0;
  const projectData = projects.slice(0, 8).map((project) => ({ name: project.title.slice(0, 14), progresso: project.progress || 0 }));
  const riskData = ['high', 'medium', 'low'].map((severity) => ({ name: severity === 'high' ? 'Críticos' : severity === 'medium' ? 'Atenção' : 'Baixos', value: risks.filter((risk) => risk.severity === severity).length }));
  const flowData = weeklyData.map((item) => ({ name: item.label || item.week, receitas: item.revenue, despesas: item.expenses, saldo: item.revenue - item.expenses }));
  const activityData = [{ name: 'Hábitos', valor: habitScore }, { name: 'Produtividade', valor: productivityScore }, { name: 'Risco controlado', valor: Math.max(0, 100 - riskScore) }];
  const totalValue = income + expenses + Math.max(balance, 0);
  const summary = useMemo(() => [{ label: 'Receitas', value: money(income), icon: CircleDollarSign, color: '#10B981' }, { label: 'Despesas', value: money(expenses), icon: Activity, color: '#F97316' }, { label: 'Projetos ativos', value: String(projects.filter((project) => project.status === 'active').length), icon: BriefcaseBusiness, color: '#00C9FF' }, { label: 'Saldo calculado', value: money(balance), icon: Target, color: balance >= 1000 ? '#10B981' : '#EF4444' }], [income, expenses, balance, projects]);
  return <div className="mx-auto w-full max-w-[1500px] space-y-6">
    <header className="rounded-2xl border border-purple-400/25 bg-gradient-to-r from-[#141024] via-card to-[#10141e] p-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.25em] text-purple-300">ANÁLISES / CENTRAL DE MÉTRICAS</p><h1 className="mt-2 text-3xl font-bold">Visão consolidada</h1><p className="mt-1 text-sm text-muted-foreground">Todos os indicadores do Founder OS, ligados às áreas que os originam.</p></div><div className="flex items-center gap-2 rounded-xl border border-purple-400/25 bg-purple-400/5 px-4 py-3"><BarChart3 className="h-5 w-5 text-purple-300" /><span className="text-sm text-muted-foreground">Atualização em tempo real</span></div></div></header>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{summary.map(({ label, value, icon: Icon, color }) => <div key={label} className="rounded-xl border border-border/70 bg-card/70 p-4"><div className="flex items-center justify-between"><span className="text-xs text-muted-foreground">{label}</span><Icon className="h-4 w-4" style={{ color }} /></div><p className="mt-2 text-2xl font-bold" style={{ color }}>{value}</p></div>)}</section>
    <section className="grid gap-6 xl:grid-cols-[1.6fr_1fr]"><ChartCard title="Fluxo financeiro" subtitle="Receitas, despesas e saldo por período"><ResponsiveContainer width="100%" height="100%"><AreaChart data={flowData}><CartesianGrid stroke="rgba(148,163,184,.09)" vertical={false} /><XAxis dataKey="name" tick={{ fill: '#94a3b8', fontSize: 10 }} /><YAxis tick={{ fill: '#94a3b8', fontSize: 10 }} /><Tooltip contentStyle={chartTip} /><Area dataKey="receitas" stroke="#10B981" fill="#10B981" fillOpacity={.12} /><Area dataKey="despesas" stroke="#F97316" fill="#F97316" fillOpacity={.1} /><Line dataKey="saldo" stroke="#00C9FF" strokeWidth={2} /></AreaChart></ResponsiveContainer></ChartCard><ChartCard title="Execução pessoal" subtitle="Hábitos, produtividade e controle de risco"><ResponsiveContainer width="100%" height="100%"><BarChart data={activityData} layout="vertical"><CartesianGrid stroke="rgba(148,163,184,.09)" horizontal={false} /><XAxis type="number" domain={[0, 100]} tick={{ fill: '#94a3b8', fontSize: 10 }} /><YAxis dataKey="name" type="category" width={95} tick={{ fill: '#94a3b8', fontSize: 10 }} /><Tooltip contentStyle={chartTip} formatter={(value) => [`${value}%`, 'Índice']} /><Bar dataKey="valor" radius={[0, 5, 5, 0]}>{activityData.map((_, index) => <Cell key={index} fill={colors[index]} />)}</Bar></BarChart></ResponsiveContainer></ChartCard></section>
    <section className="grid gap-6 xl:grid-cols-3"><ChartCard title="Projetos e progresso" subtitle="Acompanhamento dos projetos cadastrados"><ResponsiveContainer width="100%" height="100%"><BarChart data={projectData}><CartesianGrid stroke="rgba(148,163,184,.09)" vertical={false} /><XAxis dataKey="name" tick={{ fill: '#94a3b8', fontSize: 9 }} /><YAxis domain={[0, 100]} tick={{ fill: '#94a3b8', fontSize: 10 }} /><Tooltip contentStyle={chartTip} formatter={(value) => [`${value}%`, 'Progresso']} /><Bar dataKey="progresso" fill="#00C9FF" radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer></ChartCard><ChartCard title="Panorama de riscos" subtitle="Distribuição atual dos alertas"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={riskData} dataKey="value" nameKey="name" innerRadius={48} outerRadius={76} paddingAngle={4}>{riskData.map((_, index) => <Cell key={index} fill={['#EF4444', '#F97316', '#10B981'][index]} />)}</Pie><Tooltip contentStyle={chartTip} /></PieChart></ResponsiveContainer></ChartCard><ChartCard title="Áreas da vida" subtitle="Indicadores de equilíbrio pessoal"><ResponsiveContainer width="100%" height="100%"><LineChart data={lifeAreas.map((area) => ({ name: area.name.slice(0, 10), valor: area.score }))}><CartesianGrid stroke="rgba(148,163,184,.09)" vertical={false} /><XAxis dataKey="name" tick={{ fill: '#94a3b8', fontSize: 9 }} /><YAxis domain={[0, 100]} tick={{ fill: '#94a3b8', fontSize: 10 }} /><Tooltip contentStyle={chartTip} /><Line type="monotone" dataKey="valor" stroke="#A855F7" strokeWidth={2} dot={{ fill: '#A855F7' }} /></LineChart></ResponsiveContainer></ChartCard></section>
    <section className="grid gap-4 md:grid-cols-3"><Insight icon={ListChecks} title="Hábitos" text={`${habits.length} hábitos cadastrados e ${habitScore}% de execução registrada.`} color="#00C9FF" /><Insight icon={Target} title="Identidade" text={`A consolidação atual combina rotina e entregas em ${Math.round((habitScore + productivityScore) / 2)}%.`} color="#A855F7" /><Insight icon={ShieldAlert} title="Riscos" text={`${risks.length} alertas monitorados, com índice de risco de ${riskScore}%.`} color="#EF4444" /></section>
  </div>;
}

function ChartCard({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) { return <div className="rounded-xl border border-border/70 bg-card/70 p-5"><div className="mb-3"><h2 className="font-semibold">{title}</h2><p className="text-xs text-muted-foreground">{subtitle}</p></div><div className="h-64">{children}</div></div>; }
function Insight({ icon: Icon, title, text, color }: { icon: typeof Activity; title: string; text: string; color: string }) { return <div className="rounded-xl border border-border/70 bg-card/70 p-4"><Icon className="h-5 w-5" style={{ color }} /><p className="mt-3 font-semibold">{title}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{text}</p></div>; }
