import { Link, useRoute } from 'wouter';
import { ArrowLeft, ExternalLink, Pencil } from 'lucide-react';
import { useAppStore } from '@/store/useAppStore';
import { Button } from '@/components/ui/button';

export default function FinancialAccount() {
  const [, params] = useRoute('/financeiro/conta/:id');
  const { modules, openAddModal } = useAppStore();
  const account = modules.find((module) => module.id === params?.id && module.type === 'financial_account');
  if (!account) return <div className="rounded-xl border border-border p-8 text-center">Conta não encontrada.</div>;
  return <div className="max-w-[1100px] space-y-6"><Link href="/financeiro" className="inline-flex items-center gap-2 text-sm text-primary"><ArrowLeft className="h-4 w-4" /> Voltar para Financeiro</Link><header className="overflow-hidden rounded-xl border border-primary/30 bg-card shadow-[0_0_28px_#00c9ff12]"><div className="h-48 bg-gradient-to-br from-[#102d40] to-[#07101a]">{account.thumbnail && <img src={account.thumbnail} alt={`Cartão da conta ${account.title}`} className="h-full w-full object-cover opacity-90" />}</div><div className="flex flex-wrap items-center justify-between gap-4 p-6"><div><p className="text-xs uppercase tracking-wider text-primary">Conta financeira</p><h1 className="mt-1 text-3xl font-bold">{account.title}</h1><p className="text-sm text-muted-foreground">{account.accountType || 'Conta'} · {account.currency || 'BRL'}</p></div><div className="text-right"><p className="text-xs text-muted-foreground">Saldo atual</p><p className="text-3xl font-bold text-primary">R$ {(account.balance || 0).toLocaleString('pt-BR')}</p></div></div></header><div className="grid gap-4 md:grid-cols-3"><div className="rounded-lg border border-border bg-card p-5"><p className="text-xs text-muted-foreground">Saldo disponível</p><p className="mt-2 text-2xl font-bold">R$ {(account.balance || 0).toLocaleString('pt-BR')}</p></div><div className="rounded-lg border border-border bg-card p-5"><p className="text-xs text-muted-foreground">Tipo</p><p className="mt-2 text-lg font-semibold">{account.accountType || 'Não definido'}</p></div><div className="flex items-center justify-between rounded-lg border border-border bg-card p-5"><div><p className="text-xs text-muted-foreground">Imagem da conta</p><p className="mt-2 text-sm">{account.thumbnail ? 'Cartão cadastrado' : 'Nenhuma imagem'}</p></div><Button variant="outline" size="sm" onClick={() => openAddModal('financial_account', account)}><Pencil className="mr-2 h-3.5 w-3.5" /> Editar</Button></div></div><section className="rounded-xl border border-border bg-card p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Movimentações da conta</h2><p className="text-xs text-muted-foreground">Extrato filtrado para {account.title} será conectado aqui.</p></div><ExternalLink className="h-4 w-4 text-primary" /></div></section></div>;
}
