import { useMemo, useState } from 'react';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { CalendarDays, Check, ClipboardCheck, Minus, Sparkles, X } from 'lucide-react';
import { useAppStore, type IdentityStatus } from '@/store/useAppStore';

const keyOf = (date: Date) => date.toISOString().slice(0, 10);
const scoreOf: Record<IdentityStatus, number> = { done: 1, partial: .5, missed: 0 };
const daysOf = (period: 'week' | 'month' | 'previousMonth') => { const now = new Date(); now.setHours(12, 0, 0, 0); if (period === 'week') { const monday = new Date(now); monday.setDate(now.getDate() - ((now.getDay() + 6) % 7)); return Array.from({ length: 7 }, (_, index) => { const date = new Date(monday); date.setDate(monday.getDate() + index); return date; }); } const offset = period === 'previousMonth' ? -1 : 0; const first = new Date(now.getFullYear(), now.getMonth() + offset, 1, 12); const total = new Date(now.getFullYear(), now.getMonth() + offset + 1, 0).getDate(); return Array.from({ length: total }, (_, index) => new Date(first.getFullYear(), first.getMonth(), index + 1, 12)); };
function levelFor(score: number) { if (score >= 75) return { name: 'Hauggusto IV', subtitle: 'Expansão / Excelência', color: '#F97316' }; if (score >= 50) return { name: 'Hauggusto III', subtitle: 'Estrutura / Consistência', color: '#3B82F6' }; if (score >= 25) return { name: 'Hauggusto II', subtitle: 'Em Construção', color: '#10B981' }; return { name: 'Hauggusto I', subtitle: 'Reativo / Sobrevivência', color: '#EF4444' }; }

export default function Identity() {
  const { habits } = useAppStore();
  const [period, setPeriod] = useState<'week' | 'month' | 'previousMonth'>('week');
  const days = useMemo(() => daysOf(period), [period]);
  const statusAt = (habit: typeof habits[number], date: Date) => habit.checks?.[keyOf(date)] || null;
  const chartData = days.map((date) => { const statuses = habits.map((habit) => statusAt(habit, date)).filter(Boolean) as IdentityStatus[]; return { label: date.toLocaleDateString('pt-BR', { day: '2-digit', month: 'short' }), score: statuses.length ? Math.round(statuses.reduce((sum, status) => sum + scoreOf[status], 0) / statuses.length * 100) : 0 }; });
  const tracked = chartData.filter((day) => day.score > 0); const score = tracked.length ? Math.round(tracked.reduce((sum, day) => sum + day.score, 0) / tracked.length) : 0; const level = levelFor(score);
  const statusIcon = (status: IdentityStatus | null) => status === 'done' ? <Check className="h-3.5 w-3.5" /> : status === 'partial' ? <Minus className="h-3.5 w-3.5" /> : status === 'missed' ? <X className="h-3.5 w-3.5" /> : <span>·</span>;
  const statusClass = (status: IdentityStatus | null) => status === 'done' ? 'border-emerald-500/60 bg-emerald-950/70 text-emerald-300' : status === 'partial' ? 'border-orange-500/60 bg-orange-950/70 text-orange-300' : status === 'missed' ? 'border-red-500/60 bg-red-950/70 text-red-300' : 'border-border/50 bg-background/40 text-transparent';
  return <div className="mx-auto w-full max-w-[1500px] space-y-6"><header className="rounded-2xl border border-purple-400/25 bg-gradient-to-r from-[#141024] via-card to-[#10141e] p-6"><p className="text-xs font-semibold uppercase tracking-[.25em] text-purple-300">IDENTIDADE / RESUMO</p><div className="mt-2 flex flex-wrap items-end justify-between gap-5"><div><h1 className="text-3xl font-bold">Dashboard de Identidade</h1><p className="mt-1 text-sm text-muted-foreground">Um resumo automático de quem você está sendo através dos hábitos executados.</p></div><div className="flex items-center gap-3 rounded-xl border border-border/70 bg-background/40 px-4 py-3"><CalendarDays className="h-7 w-7 text-purple-300" /><div><p className="text-2xl font-bold">{score}%</p><p className="text-xs text-muted-foreground">execução no período</p></div></div></div><div className="mt-5 flex items-center gap-4 rounded-xl border p-4" style={{ borderColor: `${level.color}66`, background: `${level.color}0d` }}><div className="h-11 w-11 rounded-full" style={{ background: level.color, boxShadow: `0 0 20px ${level.color}88` }} /><div><p className="text-xl font-bold" style={{ color: level.color }}>{level.name}</p><p className="text-sm text-muted-foreground">{level.subtitle}</p></div></div></header>
    <section className="rounded-xl border border-border/70 bg-card/70 p-5"><div className="mb-4 flex items-center justify-between gap-3"><div className="flex items-center gap-2"><Sparkles className="h-4 w-4 text-purple-300" /><div><h2 className="font-semibold">Evolução da identidade</h2><p className="text-xs text-muted-foreground">Calculada automaticamente a partir do checklist de Hábitos.</p></div></div><div className="flex gap-1 rounded-lg border border-border/70 bg-background/40 p-1"><button onClick={() => setPeriod('week')} className={`rounded-md px-3 py-1.5 text-xs ${period === 'week' ? 'bg-purple-500 text-white' : 'text-muted-foreground'}`}>Semanal</button><button onClick={() => setPeriod('month')} className={`rounded-md px-3 py-1.5 text-xs ${period === 'month' ? 'bg-purple-500 text-white' : 'text-muted-foreground'}`}>Mensal</button><button onClick={() => setPeriod('previousMonth')} className={`rounded-md px-3 py-1.5 text-xs ${period === 'previousMonth' ? 'bg-purple-500 text-white' : 'text-muted-foreground'}`}>Mês anterior</button></div></div><div className="h-56"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData}><CartesianGrid stroke="rgba(148,163,184,.09)" vertical={false} /><XAxis dataKey="label" tick={{ fill: '#94a3b8', fontSize: 11 }} /><YAxis domain={[0, 100]} tick={{ fill: '#94a3b8', fontSize: 11 }} /><Tooltip contentStyle={{ background: '#10141d', border: '1px solid #334155', borderRadius: 8 }} formatter={(value) => [`${value}%`, 'Execução']} /><Area type="monotone" dataKey="score" stroke={level.color} fill={level.color} fillOpacity={.14} strokeWidth={2} /></AreaChart></ResponsiveContainer></div></section>
    <section className="overflow-hidden rounded-xl border border-border/70 bg-card/70"><div className="border-b border-border/60 p-5"><div className="flex items-center gap-2"><ClipboardCheck className="h-5 w-5 text-purple-300" /><div><h2 className="font-semibold">Resumo do checklist de hábitos</h2><p className="text-xs text-muted-foreground">Somente leitura. Para registrar ou editar, use a aba Hábitos.</p></div></div></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] border-collapse"><thead><tr className="border-b border-border/50 text-xs text-muted-foreground"><th className="sticky left-0 z-10 bg-card px-5 py-3 text-left">Hábito</th>{days.map((date) => <th key={keyOf(date)} className="px-2 py-3 text-center"><span className="block uppercase">{date.toLocaleDateString('pt-BR', { weekday: 'short' }).replace('.', '')}</span><span>{date.getDate()}</span></th>)}</tr></thead><tbody>{habits.map((habit) => <tr key={habit.id} className="border-b border-border/40 last:border-0"><td className="sticky left-0 bg-card px-5 py-4"><p className="text-sm font-medium">{habit.title}</p><p className="text-xs text-muted-foreground">{habit.category}</p></td>{days.map((date) => { const status = statusAt(habit, date); return <td key={keyOf(date)} className="px-2 py-4 text-center"><span className={`mx-auto flex h-7 w-7 items-center justify-center rounded-md border ${statusClass(status)}`}>{statusIcon(status)}</span></td>; })}</tr>)}</tbody></table></div></section></div>;
}
