import { useMemo, useState } from 'react';
import { BookOpen, CalendarDays, Check, Clock3, GraduationCap, Pencil, Plus, Sparkles, Target, Trash2, X } from 'lucide-react';
import { useAppStore, type LearningCard } from '@/store/useAppStore';

const colors = ['#22D3EE', '#8B5CF6', '#10B981', '#F97316', '#EC4899'];
const icons: Record<string, typeof BookOpen> = { Livro: BookOpen, Faculdade: GraduationCap, IA: Sparkles, Curso: Target, Atualização: Sparkles, Outro: BookOpen };

export default function Learning() {
  const { learningCards, addLearningCard, updateLearningCard, deleteLearningCard } = useAppStore();
  const [open, setOpen] = useState(false);
  const [title, setTitle] = useState('');
  const [category, setCategory] = useState<LearningCard['category']>('Curso');
  const [description, setDescription] = useState('');
  const [nextStep, setNextStep] = useState('');
  const [dueDate, setDueDate] = useState('');

  const summary = useMemo(() => {
    const total = learningCards.length;
    const progress = total ? Math.round(learningCards.reduce((sum, card) => sum + card.progress, 0) / total) : 0;
    const active = learningCards.filter((card) => (card.status || 'Em andamento') === 'Em andamento').length;
    const completed = learningCards.filter((card) => card.status === 'Concluído').length;
    return { total, progress, active, completed };
  }, [learningCards]);

  const byCategory = useMemo(() => Object.entries(learningCards.reduce<Record<string, { total: number; progress: number }>>((result, card) => {
    const current = result[card.category] || { total: 0, progress: 0 };
    result[card.category] = { total: current.total + 1, progress: current.progress + card.progress };
    return result;
  }, {})).map(([name, value]) => ({ name, ...value, average: value.total ? Math.round(value.progress / value.total) : 0 })), [learningCards]);

  const add = () => {
    if (!title.trim()) return;
    addLearningCard({ title: title.trim(), category, description: description.trim() || 'Novo tema para desenvolver.', progress: 0, color: colors[learningCards.length % colors.length], status: 'Em andamento', nextStep: nextStep.trim() || 'Definir o próximo estudo', dueDate });
    setTitle(''); setDescription(''); setNextStep(''); setDueDate(''); setCategory('Curso'); setOpen(false);
  };

  return <div className="mx-auto w-full max-w-[1500px] space-y-6">
    <header className="rounded-2xl border border-violet-400/25 bg-gradient-to-r from-[#120d22] via-card to-[#111421] p-6">
      <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.25em] text-violet-300">DESENVOLVIMENTO / REPERTÓRIO</p><h1 className="mt-2 text-3xl font-bold">Aprendizado</h1><p className="mt-1 text-sm text-muted-foreground">Organize cursos, faculdade, livros e competências com uma próxima ação clara.</p></div><button onClick={() => setOpen(true)} className="inline-flex items-center gap-2 rounded-xl bg-violet-500 px-4 py-3 text-sm font-semibold text-white shadow-[0_0_18px_rgba(139,92,246,.3)]"><Plus className="h-4 w-4" />Adicionar card</button></div>
      <div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Summary label="Progresso geral" value={`${summary.progress}%`} detail="média dos cards" color="#A78BFA" /><Summary label="Em andamento" value={summary.active} detail="frentes ativas" color="#22D3EE" /><Summary label="Concluídos" value={summary.completed} detail="cards finalizados" color="#10B981" /><Summary label="Próximo foco" value={learningCards[0]?.title || 'Adicionar estudo'} detail={learningCards[0]?.nextStep || 'Defina uma próxima ação'} color="#F97316" /></div>
    </header>

    <section className="grid gap-4 xl:grid-cols-[1.35fr_.65fr]">
      <div className="rounded-2xl border border-violet-400/20 bg-card/70 p-5"><div className="mb-4 flex items-center justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-violet-300">Mapa de evolução</p><h2 className="mt-1 text-lg font-semibold">Progresso por categoria</h2></div><Sparkles className="h-5 w-5 text-violet-300" /></div><div className="space-y-4">{byCategory.map((item, index) => <div key={item.name}><div className="mb-1.5 flex items-center justify-between text-xs"><span className="text-foreground/85">{item.name}</span><span className="font-semibold" style={{ color: colors[index % colors.length] }}>{item.average}%</span></div><div className="h-2 overflow-hidden rounded-full bg-background"><div className="h-full rounded-full transition-all" style={{ width: `${item.average}%`, background: colors[index % colors.length] }} /></div></div>)}{byCategory.length === 0 && <p className="text-sm text-muted-foreground">Adicione seu primeiro curso, livro ou tema.</p>}</div></div>
      <div className="rounded-2xl border border-violet-400/20 bg-[#15131d]/80 p-5"><div className="flex items-center gap-2 text-violet-300"><CalendarDays className="h-4 w-4" /><p className="text-[10px] font-semibold uppercase tracking-[.2em]">Foco de hoje</p></div><h2 className="mt-4 text-lg font-semibold">{learningCards.find((card) => card.status !== 'Concluído')?.title || 'Nenhum estudo pendente'}</h2><p className="mt-2 text-xs leading-relaxed text-muted-foreground">{learningCards.find((card) => card.status !== 'Concluído')?.nextStep || 'Adicione um card para definir o que estudar hoje.'}</p><div className="mt-5 flex items-center gap-2 text-xs text-muted-foreground"><Clock3 className="h-3.5 w-3.5 text-violet-300" /> Reserve um bloco de concentração para avançar.</div></div>
    </section>

    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{learningCards.map((card) => <LearningCardView key={card.id} card={card} onUpdate={updateLearningCard} onDelete={deleteLearningCard} />)}<button onClick={() => setOpen(true)} className="flex min-h-[280px] flex-col items-center justify-center rounded-2xl border border-dashed border-violet-400/40 bg-violet-500/5 text-violet-300 transition hover:bg-violet-500/10"><Plus className="h-8 w-8" /><span className="mt-3 font-medium">Adicionar novo aprendizado</span><span className="mt-1 text-xs text-muted-foreground">Curso, livro, habilidade ou projeto</span></button></section>

    {open && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4"><div className="w-full max-w-lg rounded-2xl border border-violet-400/40 bg-[#15131d] p-6 shadow-2xl"><div className="flex items-center justify-between"><div><h2 className="text-xl font-semibold">Novo aprendizado</h2><p className="mt-1 text-xs text-muted-foreground">Crie um card com a próxima ação do estudo.</p></div><button onClick={() => setOpen(false)} className="rounded-lg p-2 text-muted-foreground hover:bg-white/5"><X className="h-5 w-5" /></button></div><div className="mt-5 space-y-3"><input autoFocus value={title} onChange={(event) => setTitle(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') add(); if (event.key === 'Escape') setOpen(false); }} placeholder="Nome do curso, livro ou tema" className="h-11 w-full rounded-lg border border-border bg-background px-3 text-sm outline-none focus:border-violet-400" /><select value={category} onChange={(event) => setCategory(event.target.value as LearningCard['category'])} className="h-11 w-full rounded-lg border border-border bg-background px-3 text-sm outline-none focus:border-violet-400"><option>Curso</option><option>Faculdade</option><option>Livro</option><option>Atualização</option><option>IA</option><option>Outro</option></select><textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="O que você precisa aprender?" className="min-h-20 w-full resize-none rounded-lg border border-border bg-background p-3 text-sm outline-none focus:border-violet-400" /><input value={nextStep} onChange={(event) => setNextStep(event.target.value)} placeholder="Próxima ação" className="h-11 w-full rounded-lg border border-border bg-background px-3 text-sm outline-none focus:border-violet-400" /><input type="date" value={dueDate} onChange={(event) => setDueDate(event.target.value)} className="h-11 w-full rounded-lg border border-border bg-background px-3 text-sm text-foreground outline-none focus:border-violet-400" /><div className="flex justify-end gap-2 pt-2"><button onClick={() => setOpen(false)} className="rounded-lg border border-border px-4 py-2 text-sm text-muted-foreground">Cancelar</button><button onClick={add} className="rounded-lg bg-violet-500 px-4 py-2 text-sm font-semibold text-white">Criar card</button></div></div></div></div>}
  </div>;
}

function Summary({ label, value, detail, color }: { label: string; value: string | number; detail: string; color: string }) { return <div className="rounded-xl border border-border/70 bg-background/35 p-3"><p className="text-[10px] uppercase tracking-wider text-muted-foreground">{label}</p><p className="mt-2 truncate text-lg font-bold" style={{ color }}>{value}</p><p className="mt-1 truncate text-[10px] text-muted-foreground">{detail}</p></div>; }

function LearningCardView({ card, onUpdate, onDelete }: { card: LearningCard; onUpdate: (id: string, updates: Partial<LearningCard>) => void; onDelete: (id: string) => void }) {
  const Icon = icons[card.category] || BookOpen;
  const status = card.status || 'Em andamento';
  return <article className="group rounded-2xl border border-border/70 bg-card/70 p-5 transition hover:-translate-y-1 hover:border-violet-400/50" style={{ boxShadow: `inset 0 2px 0 ${card.color}99` }}><div className="flex items-start justify-between gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-xl border" style={{ color: card.color, borderColor: `${card.color}66`, background: `${card.color}12` }}><Icon className="h-5 w-5" /></div><div className="flex items-center gap-1"><select value={status} onChange={(event) => onUpdate(card.id, { status: event.target.value as LearningCard['status'] })} className="rounded-full border border-border/70 bg-background/50 px-2 py-1 text-[10px] text-muted-foreground outline-none"><option>Em andamento</option><option>Pausado</option><option>Concluído</option></select><button type="button" onClick={() => onDelete(card.id)} className="rounded-md p-1.5 text-muted-foreground opacity-0 transition hover:bg-red-500/10 hover:text-red-300 group-hover:opacity-100" aria-label={`Excluir ${card.title}`}><Trash2 className="h-3.5 w-3.5" /></button></div></div><input value={card.title} onChange={(event) => onUpdate(card.id, { title: event.target.value })} className="mt-5 w-full bg-transparent text-lg font-semibold text-foreground outline-none focus:border-b focus:border-violet-400" /><p className="mt-1 min-h-10 text-sm text-muted-foreground">{card.description}</p><div className="mt-4 flex items-center justify-between gap-2 text-xs"><span className="text-muted-foreground">Progresso</span><span style={{ color: card.color }}>{card.progress}%</span></div><input type="range" min="0" max="100" value={card.progress} onChange={(event) => onUpdate(card.id, { progress: Number(event.target.value) })} className="mt-2 w-full accent-violet-400" /><div className="mt-4 flex items-center gap-2 text-[11px] text-muted-foreground"><Pencil className="h-3.5 w-3.5" /><input value={card.nextStep || ''} onChange={(event) => onUpdate(card.id, { nextStep: event.target.value })} placeholder="Próxima ação" className="min-w-0 flex-1 bg-transparent outline-none focus:border-b focus:border-violet-400" /></div>{card.dueDate && <p className="mt-3 flex items-center gap-1.5 text-[10px] text-muted-foreground"><CalendarDays className="h-3 w-3" /> Prazo: {new Date(`${card.dueDate}T12:00:00`).toLocaleDateString('pt-BR')}</p>}<div className="mt-4 flex items-center justify-between border-t border-border/50 pt-3 text-[10px] text-muted-foreground"><span>{card.category}</span>{status === 'Concluído' && <span className="flex items-center gap-1 text-emerald-300"><Check className="h-3 w-3" /> concluído</span>}</div></article>;
}
