import { useState } from 'react';
import { BookOpen, GraduationCap, Plus, Sparkles, Target, X } from 'lucide-react';
import { useAppStore, type LearningCard } from '@/store/useAppStore';

const colors = ['#22D3EE', '#8B5CF6', '#10B981', '#F97316', '#EC4899'];
const icons: Record<string, typeof BookOpen> = { Livro: BookOpen, Faculdade: GraduationCap, IA: Sparkles, Curso: Target, Atualização: Sparkles, Outro: BookOpen };

export default function Learning() {
  const { learningCards, addLearningCard } = useAppStore();
  const [open, setOpen] = useState(false);
  const [title, setTitle] = useState('');
  const [category, setCategory] = useState<LearningCard['category']>('Curso');
  const [description, setDescription] = useState('');
  const add = () => { if (!title.trim()) return; addLearningCard({ title: title.trim(), category, description: description.trim() || 'Novo tema para desenvolver.', progress: 0, color: colors[learningCards.length % colors.length] }); setTitle(''); setDescription(''); setCategory('Curso'); setOpen(false); };
  return <div className="mx-auto w-full max-w-[1500px] space-y-6"><header className="rounded-2xl border border-violet-400/25 bg-gradient-to-r from-[#120d22] via-card to-[#111421] p-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.25em] text-violet-300">DESENVOLVIMENTO / REPERTÓRIO</p><h1 className="mt-2 text-3xl font-bold">Aprendizado</h1><p className="mt-1 text-sm text-muted-foreground">Organize cursos, faculdade, livros e competências que você quer desenvolver.</p></div><button onClick={() => setOpen(true)} className="inline-flex items-center gap-2 rounded-xl bg-violet-500 px-4 py-3 text-sm font-semibold text-white shadow-[0_0_18px_rgba(139,92,246,.3)]"><Plus className="h-4 w-4" />Adicionar card</button></div></header>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{learningCards.map((card) => { const Icon = icons[card.category] || BookOpen; return <article key={card.id} className="group rounded-2xl border border-border/70 bg-card/70 p-5 transition hover:-translate-y-1 hover:border-violet-400/50" style={{ boxShadow: `inset 0 2px 0 ${card.color}99` }}><div className="flex items-start justify-between gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-xl border" style={{ color: card.color, borderColor: `${card.color}66`, background: `${card.color}12` }}><Icon className="h-5 w-5" /></div><span className="rounded-full border border-border/70 px-2.5 py-1 text-[10px] uppercase tracking-wider text-muted-foreground">{card.category}</span></div><h2 className="mt-5 text-lg font-semibold">{card.title}</h2><p className="mt-1 min-h-10 text-sm text-muted-foreground">{card.description}</p><div className="mt-5 flex items-center justify-between text-xs"><span className="text-muted-foreground">Progresso</span><span style={{ color: card.color }}>{card.progress}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-background"><div className="h-full rounded-full" style={{ width: `${card.progress}%`, background: card.color, boxShadow: `0 0 10px ${card.color}` }} /></div><p className="mt-4 text-xs text-muted-foreground">Atualize o progresso na próxima etapa do módulo.</p></article>; })}<button onClick={() => setOpen(true)} className="flex min-h-[260px] flex-col items-center justify-center rounded-2xl border border-dashed border-violet-400/40 bg-violet-500/5 text-violet-300 transition hover:bg-violet-500/10"><Plus className="h-8 w-8" /><span className="mt-3 font-medium">Adicionar novo aprendizado</span><span className="mt-1 text-xs text-muted-foreground">Curso, livro, habilidade ou projeto</span></button></section>
    {open && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4"><div className="w-full max-w-lg rounded-2xl border border-violet-400/40 bg-[#15131d] p-6 shadow-2xl"><div className="flex items-center justify-between"><div><h2 className="text-xl font-semibold">Novo aprendizado</h2><p className="mt-1 text-xs text-muted-foreground">Crie um card para acompanhar seu desenvolvimento.</p></div><button onClick={() => setOpen(false)} className="rounded-lg p-2 text-muted-foreground hover:bg-white/5"><X className="h-5 w-5" /></button></div><div className="mt-5 space-y-4"><input autoFocus value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Nome do curso, livro ou tema" className="h-11 w-full rounded-lg border border-border bg-background px-3 text-sm outline-none focus:border-violet-400" /><select value={category} onChange={(event) => setCategory(event.target.value as LearningCard['category'])} className="h-11 w-full rounded-lg border border-border bg-background px-3 text-sm outline-none focus:border-violet-400"><option>Curso</option><option>Faculdade</option><option>Livro</option><option>Atualização</option><option>IA</option><option>Outro</option></select><textarea value={description} onChange={(event) => setDescription(event.target.value)} placeholder="O que você precisa aprender?" className="min-h-24 w-full resize-none rounded-lg border border-border bg-background p-3 text-sm outline-none focus:border-violet-400" /><div className="flex justify-end gap-2"><button onClick={() => setOpen(false)} className="rounded-lg border border-border px-4 py-2 text-sm text-muted-foreground">Cancelar</button><button onClick={add} className="rounded-lg bg-violet-500 px-4 py-2 text-sm font-semibold text-white">Criar card</button></div></div></div></div>}
  </div>;
}
