import { useMemo, useState } from 'react';
import { CalendarDays, ChevronLeft, ChevronRight } from 'lucide-react';

const months = ['janeiro', 'fevereiro', 'março', 'abril', 'maio', 'junho', 'julho', 'agosto', 'setembro', 'outubro', 'novembro', 'dezembro'];
const weekdays = ['D', 'S', 'T', 'Q', 'Q', 'S', 'S'];

export function ModernCalendar() {
  const today = new Date();
  const [month, setMonth] = useState(new Date(today.getFullYear(), today.getMonth(), 1));
  const [selected, setSelected] = useState(today.getDate());
  const days = useMemo(() => { const first = new Date(month.getFullYear(), month.getMonth(), 1).getDay(); const total = new Date(month.getFullYear(), month.getMonth() + 1, 0).getDate(); return [...Array(first).fill(null), ...Array.from({ length: total }, (_, index) => index + 1)]; }, [month]);
  const move = (amount: number) => { setMonth(new Date(month.getFullYear(), month.getMonth() + amount, 1)); setSelected(1); };
  return <section className="w-full rounded-xl border border-[#00C9FF35] bg-[#07101a]/80 p-3 shadow-[0_0_22px_#00c9ff0a] lg:w-[310px]"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><span className="flex h-8 w-8 items-center justify-center rounded-lg border border-[#00C9FF55] bg-[#00C9FF12] text-primary"><CalendarDays className="h-4 w-4" /></span><div><p className="text-[9px] uppercase tracking-wider text-primary">Agenda</p><p className="text-xs font-semibold capitalize">{months[month.getMonth()]} {month.getFullYear()}</p></div></div><div className="flex items-center gap-1"><button onClick={() => move(-1)} className="rounded-md p-1 text-muted-foreground hover:bg-primary/10 hover:text-primary"><ChevronLeft className="h-3.5 w-3.5" /></button><button onClick={() => { setMonth(new Date(today.getFullYear(), today.getMonth(), 1)); setSelected(today.getDate()); }} className="rounded border border-primary/30 px-2 py-1 text-[9px] text-primary hover:bg-primary/10">Hoje</button><button onClick={() => move(1)} className="rounded-md p-1 text-muted-foreground hover:bg-primary/10 hover:text-primary"><ChevronRight className="h-3.5 w-3.5" /></button></div></div><div className="calendar-grid mt-3 grid grid-cols-7 gap-1">{weekdays.map((day, index) => <span key={`${day}-${index}`} className="text-center text-[9px] font-semibold text-muted-foreground">{day}</span>)}{days.map((day, index) => <button key={`${month.toISOString()}-${index}`} disabled={!day} onClick={() => day && setSelected(day)} className={`h-7 rounded-md text-[10px] transition ${!day ? 'cursor-default' : 'hover:bg-primary/10 hover:text-primary'} ${day === selected ? 'bg-primary text-primary-foreground shadow-[0_0_9px_#00c9ff55]' : ''}`}>{day}</button>)}</div><p className="mt-2 text-right text-[9px] text-muted-foreground">Selecionado: <span className="text-primary">{selected}/{month.getMonth() + 1}</span></p></section>;
}
