import { useMemo, useState } from 'react';
import { CalendarDays, Check, ChevronLeft, ChevronRight, Circle, ListTodo } from 'lucide-react';
import { useAppStore } from '@/store/useAppStore';

const months = ['janeiro', 'fevereiro', 'março', 'abril', 'maio', 'junho', 'julho', 'agosto', 'setembro', 'outubro', 'novembro', 'dezembro'];
const weekdays = ['D', 'S', 'T', 'Q', 'Q', 'S', 'S'];
type CalendarView = 'daily' | 'weekly' | 'monthly';

function dateKey(date: Date) { return date.toISOString().slice(0, 10); }
function startOfWeek(date: Date) { const result = new Date(date); result.setDate(result.getDate() - result.getDay()); result.setHours(12, 0, 0, 0); return result; }

export function ModernCalendar() {
  const today = new Date();
  const { agenda, nextActions, habits, productivityHabits, toggleAgendaItem, toggleNextAction } = useAppStore();
  const [month, setMonth] = useState(new Date(today.getFullYear(), today.getMonth(), 1));
  const [selected, setSelected] = useState(dateKey(today));
  const [view, setView] = useState<CalendarView>('daily');
  const days = useMemo(() => { const first = new Date(month.getFullYear(), month.getMonth(), 1).getDay(); const total = new Date(month.getFullYear(), month.getMonth() + 1, 0).getDate(); return [...Array(first).fill(null), ...Array.from({ length: total }, (_, index) => index + 1)]; }, [month]);
  const selectedDate = new Date(`${selected}T12:00:00`);
  const visibleDates = useMemo(() => { if (view === 'daily') return [selected]; if (view === 'weekly') return Array.from({ length: 7 }, (_, index) => { const date = startOfWeek(selectedDate); date.setDate(date.getDate() + index); return dateKey(date); }); return Array.from({ length: new Date(selectedDate.getFullYear(), selectedDate.getMonth() + 1, 0).getDate() }, (_, index) => dateKey(new Date(selectedDate.getFullYear(), selectedDate.getMonth(), index + 1))); }, [selected, view]);
  const entries = useMemo(() => {
    const agendaEntries = agenda.filter((item) => visibleDates.includes(item.date || dateKey(today))).map((item) => ({ id: item.id, title: item.title, meta: `${item.time} · ${item.type}`, done: item.done, color: item.type === 'meeting' ? '#A855F7' : item.type === 'presencial' ? '#FACC15' : '#10B981', action: () => toggleAgendaItem(item.id) }));
    const actionEntries = nextActions.filter((item) => item.date && visibleDates.includes(item.date)).map((item) => ({ id: item.id, title: item.text, meta: item.priority === 'urgent' ? 'Urgente' : 'Próxima ação', done: item.done, color: item.priority === 'urgent' ? '#F97316' : '#00C9FF', action: () => toggleNextAction(item.id) }));
    const habitEntries = [...habits, ...productivityHabits].filter((item, index, list) => list.findIndex((candidate) => candidate.id === item.id) === index).filter((item) => visibleDates.some((date) => item.checks?.[date] === 'done')).map((item) => ({ id: `habit-${item.id}`, title: item.title, meta: item.category, done: true, color: item.categoryColor || '#10B981', action: undefined }));
    return [...agendaEntries, ...actionEntries, ...habitEntries].slice(0, view === 'daily' ? 5 : 8);
  }, [agenda, nextActions, habits, productivityHabits, visibleDates, view, toggleAgendaItem, toggleNextAction]);
  const move = (amount: number) => { const next = new Date(month.getFullYear(), month.getMonth() + amount, 1); setMonth(next); setSelected(dateKey(new Date(next.getFullYear(), next.getMonth(), 1))); };
  const goToday = () => { setMonth(new Date(today.getFullYear(), today.getMonth(), 1)); setSelected(dateKey(today)); };
  return <section className="w-full rounded-2xl border border-[#00C9FF35] bg-card/90 p-4 shadow-[0_0_26px_#00c9ff0a] lg:w-[350px]">
    <div className="flex items-start justify-between gap-3"><div className="flex items-center gap-2"><span className="flex h-9 w-9 items-center justify-center rounded-xl border border-[#00C9FF55] bg-[#00C9FF12] text-primary"><CalendarDays className="h-4 w-4" /></span><div><p className="text-[9px] font-semibold uppercase tracking-[.18em] text-primary">Calendário</p><p className="text-sm font-semibold capitalize">{months[month.getMonth()]} {month.getFullYear()}</p></div></div><div className="flex items-center gap-1"><button onClick={() => move(-1)} className="rounded-lg p-1.5 text-muted-foreground hover:bg-primary/10 hover:text-primary" aria-label="Mês anterior"><ChevronLeft className="h-4 w-4" /></button><button onClick={goToday} className="rounded-lg border border-primary/30 px-2 py-1 text-[10px] text-primary hover:bg-primary/10">Hoje</button><button onClick={() => move(1)} className="rounded-lg p-1.5 text-muted-foreground hover:bg-primary/10 hover:text-primary" aria-label="Próximo mês"><ChevronRight className="h-4 w-4" /></button></div></div>
    <div className="mt-3 grid grid-cols-3 gap-1 rounded-xl border border-border/70 bg-background/60 p-1">{(['daily', 'weekly', 'monthly'] as const).map((item) => <button key={item} onClick={() => setView(item)} className={`rounded-lg px-2 py-1.5 text-[10px] transition ${view === item ? 'bg-primary text-primary-foreground shadow-sm' : 'text-muted-foreground hover:text-foreground'}`}>{item === 'daily' ? 'Diário' : item === 'weekly' ? 'Semanal' : 'Mensal'}</button>)}</div>
    <div className="calendar-grid mt-3 grid grid-cols-7 gap-1">{weekdays.map((day, index) => <span key={`${day}-${index}`} className="text-center text-[9px] font-semibold text-muted-foreground">{day}</span>)}{days.map((day, index) => { const key = day ? dateKey(new Date(month.getFullYear(), month.getMonth(), day)) : ''; const isSelected = key === selected; const hasItems = Boolean(key && (agenda.some((item) => (item.date || dateKey(today)) === key) || nextActions.some((item) => item.date === key))); return <button key={`${month.toISOString()}-${index}`} disabled={!day} onClick={() => day && setSelected(key)} className={`relative h-7 rounded-lg text-[10px] transition ${!day ? 'cursor-default' : 'hover:bg-primary/10 hover:text-primary'} ${isSelected ? 'bg-primary text-primary-foreground shadow-[0_0_10px_#00c9ff55]' : ''}`}>{day}{hasItems && !isSelected && <span className="absolute bottom-0.5 left-1/2 h-1 w-1 -translate-x-1/2 rounded-full bg-amber-300" />}</button>; })}</div>
    <div className="mt-4 border-t border-border/60 pt-3"><div className="mb-2 flex items-center justify-between"><div className="flex items-center gap-1.5 text-xs font-semibold"><ListTodo className="h-3.5 w-3.5 text-primary" />{view === 'daily' ? 'Programado no dia' : view === 'weekly' ? 'Programado na semana' : 'Programado no mês'}</div><span className="text-[10px] text-muted-foreground">{new Date(`${selected}T12:00:00`).toLocaleDateString('pt-BR')}</span></div>{entries.length ? <div className="max-h-32 space-y-1.5 overflow-y-auto pr-1">{entries.map((entry) => <button key={entry.id} onClick={entry.action} disabled={!entry.action} className={`flex w-full items-center gap-2 rounded-lg border border-border/60 bg-background/45 px-2.5 py-2 text-left transition ${entry.action ? 'hover:border-primary/50' : ''}`}><span className="h-2 w-2 shrink-0 rounded-full" style={{ backgroundColor: entry.color }} />{entry.done ? <Check className="h-3 w-3 shrink-0 text-emerald-400" /> : <Circle className="h-3 w-3 shrink-0 text-muted-foreground" />}<span className={`min-w-0 flex-1 truncate text-[11px] ${entry.done ? 'text-muted-foreground line-through' : 'text-foreground'}`}>{entry.title}</span><span className="max-w-[74px] truncate text-[9px] text-muted-foreground">{entry.meta}</span></button>)}</div> : <p className="rounded-lg border border-dashed border-border/70 px-3 py-3 text-center text-[10px] text-muted-foreground">Nenhum item programado para este período.</p>}</div>
  </section>;
}
