import { Link } from 'wouter';
import { ArrowRight, FolderKanban, Plus } from 'lucide-react';
import { useAppStore } from '@/store/useAppStore';
import { Button } from '@/components/ui/button';

export function ProjectsBlock() {
  const { modules, openAddModal } = useAppStore();
  const projects = modules.filter((module) => module.type === 'project' && (module.status === 'active' || module.status === 'paused')).sort((a, b) => a.order - b.order).slice(0, 6);
  return <section className="overflow-hidden rounded-xl border border-[#00c9ff35] bg-[#07101a]/80 shadow-[0_0_22px_#00c9ff0b]"><div className="flex items-center justify-between border-b border-[#ffffff0a] px-5 py-4"><div className="flex items-center gap-2.5"><FolderKanban className="h-4 w-4 text-[#38BDF8]" style={{ filter: 'drop-shadow(0 0 5px #38BDF8)' }} /><h3 className="text-sm font-semibold uppercase tracking-[0.12em] text-foreground">Projetos ativos</h3></div><Button variant="ghost" size="sm" onClick={() => openAddModal('project')} className="h-7 gap-1 px-2 text-xs text-primary"><Plus className="h-3.5 w-3.5" /> Novo</Button></div><div className="space-y-1 p-3">{projects.map((project) => { const progress = project.progress || 0; return <div key={project.id} className="rounded-lg border border-white/[0.06] bg-black/10 px-3 py-3 transition hover:border-primary/30"><div className="flex items-center gap-2.5"><div className="min-w-0 flex-1"><p className="truncate text-xs font-medium text-foreground">{project.title}</p><p className="mt-1 text-[10px] text-muted-foreground">{project.phase || (project.status === 'paused' ? 'Pausado' : 'Em andamento')}</p></div><span className="text-xs font-semibold text-foreground">{progress}%</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-[#163342]"><div className="h-full rounded-full bg-[#22B8F0] shadow-[0_0_8px_rgba(34,184,240,.65)]" style={{ width: `${progress}%` }} /></div><p className="mt-1 truncate text-[10px] text-muted-foreground">{project.nextAction || 'Definir próxima ação'}</p></div>})}{projects.length === 0 && <p className="p-4 text-xs text-muted-foreground">Nenhum projeto ativo.</p>}</div><Link href="/projetos" className="flex items-center justify-center gap-1.5 border-t border-[#ffffff0a] px-5 py-3 text-xs font-medium text-primary transition-colors hover:bg-primary/[0.04]">Ver todos os projetos <ArrowRight className="h-3.5 w-3.5" /></Link></section>;
}
