import { useEffect, useState } from 'react';
import { CloudSun, Droplets, RefreshCw, Wind } from 'lucide-react';

type Weather = { temperature: number; humidity: number; wind: number; code: number; time: string };
const weatherText: Record<number, string> = { 0: 'Céu limpo', 1: 'Pouco nublado', 2: 'Parcialmente nublado', 3: 'Nublado', 45: 'Neblina', 48: 'Neblina', 51: 'Garoa leve', 61: 'Chuva leve', 63: 'Chuva moderada', 65: 'Chuva forte', 80: 'Pancadas de chuva', 95: 'Trovoada' };

export function WeatherWidget() {
  const [weather, setWeather] = useState<Weather | null>(null);
  const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); try { const response = await fetch('https://api.open-meteo.com/v1/forecast?latitude=-22.8427&longitude=-43.3113&current=temperature_2m,relative_humidity_2m,weather_code,wind_speed_10m&temperature_unit=celsius&wind_speed_unit=kmh&timezone=America%2FSao_Paulo'); const data = await response.json(); setWeather({ temperature: data.current.temperature_2m, humidity: data.current.relative_humidity_2m, wind: data.current.wind_speed_10m, code: data.current.weather_code, time: data.current.time }); } catch { setWeather(null); } finally { setLoading(false); } };
  useEffect(() => { load(); const timer = window.setInterval(load, 15 * 60 * 1000); return () => window.clearInterval(timer); }, []);
  return <section className="w-full rounded-xl border border-[#38BDF835] bg-[#07101a]/80 p-3 shadow-[0_0_22px_#38bdf80a] lg:w-[250px]"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><span className="flex h-8 w-8 items-center justify-center rounded-lg border border-[#38BDF855] bg-[#38BDF812] text-[#38BDF8]"><CloudSun className="h-4 w-4" /></span><div><p className="text-[9px] uppercase tracking-wider text-[#38BDF8]">Clima agora</p><p className="text-xs font-semibold">Vila da Penha, RJ</p></div></div><button onClick={load} className="rounded-md p-1 text-muted-foreground hover:bg-[#38BDF812] hover:text-[#38BDF8]" title="Atualizar clima"><RefreshCw className={`h-3.5 w-3.5 ${loading ? 'animate-spin' : ''}`} /></button></div>{loading && !weather ? <p className="mt-4 text-xs text-muted-foreground">Consultando temperatura...</p> : weather ? <><div className="mt-4 flex items-end justify-between"><div><strong className="text-3xl font-semibold text-[#38BDF8]">{Math.round(weather.temperature)}°</strong><p className="text-[10px] text-muted-foreground">{weatherText[weather.code] || 'Condição atual'}</p></div><div className="space-y-1 text-right text-[10px] text-muted-foreground"><p className="flex items-center justify-end gap-1"><Droplets className="h-3 w-3 text-[#38BDF8]" /> {weather.humidity}%</p><p className="flex items-center justify-end gap-1"><Wind className="h-3 w-3 text-[#38BDF8]" /> {Math.round(weather.wind)} km/h</p></div></div><p className="mt-3 text-[9px] text-muted-foreground">Atualizado às {weather.time.slice(11, 16)} · atualização automática</p></> : <p className="mt-4 text-xs text-red-400">Não foi possível atualizar agora.</p>}</section>;
}
