import type { AppData } from './useAppStore';

const identitySeedItems = [
  { id: 'identity-1', title: 'Cumprir minha palavra', order: 0 },
  { id: 'identity-2', title: 'Construir patrimônio', order: 1 },
  { id: 'identity-3', title: 'Aumentar minha distribuição', order: 2 },
  { id: 'identity-4', title: 'Fechar ciclos importantes', order: 3 },
  { id: 'identity-5', title: 'Fortalecer meus sistemas', order: 4 },
  { id: 'identity-distribution-evolution', title: 'Entrar em contato com processo de evolução real', order: 5 },
];

const identitySeedDay = (offset: number) => {
  const date = new Date();
  date.setHours(12, 0, 0, 0);
  date.setDate(date.getDate() - offset);
  return date.toISOString().slice(0, 10);
};

const identitySeedChecks = Array.from({ length: 28 }, (_, dayOffset) =>
  identitySeedItems.map((item, itemIndex) => {
    const pattern = (dayOffset * 2 + itemIndex) % 9;
    const status = pattern === 0 || pattern === 1 ? 'missed' : pattern === 2 || pattern === 3 ? 'partial' : 'done';
    return { id: `${item.id}-${identitySeedDay(dayOffset)}`, itemId: item.id, date: identitySeedDay(dayOffset), status } as const;
  })
).flat();

export const seedData: AppData = {
  modules: [
    // Projects
    {
      id: '1',
      type: 'project',
      title: 'Soul Krieg',
      category: 'Produtos',
      status: 'active',
      projectName: 'Soul Krieg',
      phase: 'Construção',
      nextAction: 'Gravar episódios',
      progress: 65,
      tags: ['Gaming', 'Lançamento Q2'],
      order: 0,
      createdAt: new Date('2024-01-15').toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: '2',
      type: 'project',
      title: 'Solar Machine',
      category: 'Produtos',
      status: 'active',
      projectName: 'Solar Machine',
      phase: 'Validação',
      nextAction: 'Validar MVP',
      progress: 40,
      tags: ['Hardware', 'B2B'],
      order: 1,
      createdAt: new Date('2024-02-01').toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: '3',
      type: 'project',
      title: 'Burry',
      category: 'Produtos',
      status: 'paused',
      projectName: 'Burry',
      phase: 'Construção',
      nextAction: 'Conteúdo novo',
      progress: 20,
      tags: ['SaaS', 'Pausado'],
      order: 2,
      createdAt: new Date('2023-11-20').toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: '4',
      type: 'project',
      title: '21GO',
      category: 'Produtos',
      status: 'active',
      projectName: '21GO',
      phase: 'Operação',
      nextAction: 'SEO + Conteúdo',
      progress: 80,
      tags: ['Marketplace', 'Fase Final'],
      order: 3,
      createdAt: new Date('2023-10-10').toISOString(),
      updatedAt: new Date().toISOString(),
    },
    // Metrics
    {
      id: '5',
      type: 'metric',
      title: 'Caixa Atual',
      category: 'Financeiro',
      status: 'active',
      value: 48500,
      unit: 'R$',
      trend: 'up',
      change: 8.5,
      order: 4,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: '6',
      type: 'metric',
      title: 'Projetos Ativos',
      category: 'Operações',
      status: 'active',
      value: 4,
      unit: 'projetos',
      trend: 'stable',
      order: 5,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: '7',
      type: 'metric',
      title: 'Alertas',
      category: 'Operações',
      status: 'active',
      value: 2,
      unit: 'pendentes',
      trend: 'down',
      order: 6,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    // Financial Accounts
    {
      id: '8',
      type: 'financial_account',
      title: 'Conta PJ',
      category: 'Financeiro',
      status: 'active',
      balance: 300,
      currency: 'BRL',
      accountType: 'Corrente',
      order: 7,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: '9',
      type: 'financial_account',
      title: 'Conta PF',
      category: 'Financeiro',
      status: 'active',
      balance: 11500,
      currency: 'BRL',
      accountType: 'Corrente',
      order: 8,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: '10',
      type: 'financial_account',
      title: 'Reserva',
      category: 'Financeiro',
      status: 'active',
      balance: 5000,
      currency: 'BRL',
      accountType: 'Poupança',
      order: 9,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
  categories: [
    { id: 'cat-1', name: 'Produtos', order: 0 },
    { id: 'cat-2', name: 'Financeiro', order: 1 },
    { id: 'cat-3', name: 'Operações', order: 2 },
  ],
  weeklyData: [
    { week: '2024-W24', revenue: 12500, expenses: 8200, label: 'Sem 24' },
    { week: '2024-W25', revenue: 15800, expenses: 9100, label: 'Sem 25' },
    { week: '2024-W26', revenue: 18200, expenses: 11500, label: 'Sem 26' },
    { week: '2024-W27', revenue: 14100, expenses: 8900, label: 'Sem 27' },
    { week: '2024-W28', revenue: 21300, expenses: 12800, label: 'Sem 28' },
    { week: '2024-W29', revenue: 19700, expenses: 10200, label: 'Sem 29' },
  ],
  transactions: [
    { id: 'tx-1', description: 'Recebimento Solar Machine', amount: 9800, type: 'income', category: 'Vendas', account: 'Conta PJ', status: 'paid', date: '2024-06-07T10:24:00' },
    { id: 'tx-2', description: 'Recebimento Soul Krieg', amount: 5200, type: 'income', category: 'Projetos', account: 'Conta PJ', status: 'paid', date: '2024-06-06T14:10:00' },
    { id: 'tx-3', description: 'Consultoria estratégica', amount: 2800, type: 'income', category: 'Serviços', account: 'Conta PF', status: 'paid', date: '2024-06-05T09:15:00' },
    { id: 'tx-4', description: 'Folha e prestadores', amount: 6400, type: 'expense', category: 'Pessoas', account: 'Conta PJ', status: 'paid', date: '2024-06-07T08:20:00' },
    { id: 'tx-5', description: 'Ferramentas e assinaturas', amount: 890, type: 'expense', category: 'Operação', account: 'Conta PJ', status: 'paid', date: '2024-06-06T11:30:00' },
    { id: 'tx-6', description: 'Mídia e distribuição', amount: 1250, type: 'expense', category: 'Marketing', account: 'Conta PJ', status: 'pending', date: '2024-06-05T16:45:00' },
    { id: 'tx-7', description: 'Impostos do mês', amount: 740, type: 'expense', category: 'Impostos', account: 'Conta PJ', status: 'paid', date: '2024-06-04T10:05:00' },
    { id: 'tx-8', description: 'Reembolso de viagem', amount: 320, type: 'expense', category: 'Deslocamento', account: 'Conta PF', status: 'refunded', date: '2024-06-03T13:40:00' },
  ],
  financialSummary: {},
  quickCaptures: [
    {
      id: 'qc-1',
      text: 'Revisar proposta Solar Machine - cliente respondeu',
      createdAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    },
    {
      id: 'qc-2',
      text: 'Agendar call com investidor próxima terça',
      createdAt: new Date(Date.now() - 3600000 * 5).toISOString(),
    },
  ],
  weekFocus: 'Fechar contrato Solar Machine',
  priorities: [
    { id: 'p-1', text: 'Revisar métricas de Soul Krieg', done: false, order: 0 },
    { id: 'p-2', text: 'Finalizar deck de investimento', done: true, order: 1 },
    { id: 'p-3', text: 'Call com equipe 21GO - 15h', done: false, order: 2 },
  ],
  habits: [
    { id: 'h-1', title: 'Meditação 10min', done: false, streak: 7, category: 'Saúde', order: 0 },
    { id: 'h-2', title: 'Revisão de métricas', done: true, streak: 12, category: 'Operações', order: 1 },
    { id: 'h-3', title: 'Leitura 30min', done: false, streak: 3, category: 'Aprendizado', order: 2 },
    { id: 'h-4', title: 'Exercício físico', done: false, streak: 5, category: 'Saúde', order: 3 },
  ],
  agenda: [
    { id: 'ag-1', title: 'Call investidor — Solar Machine', time: '09:30', type: 'meeting', done: false },
    { id: 'ag-2', title: 'Revisão de deck 21GO', time: '11:00', type: 'task', done: true },
    { id: 'ag-3', title: 'Almoço com sócio', time: '13:00', type: 'meeting', done: false },
    { id: 'ag-4', title: 'Sprint review Soul Krieg', time: '16:00', type: 'meeting', done: false },
  ],
  lifeAreas: [
    { id: 'la-1', name: 'Financeiro', score: 72, color: '#00C9FF' },
    { id: 'la-2', name: 'Projetos', score: 85, color: '#8B5CF6' },
    { id: 'la-3', name: 'Saúde', score: 60, color: '#10B981' },
    { id: 'la-4', name: 'Relações', score: 55, color: '#F97316' },
    { id: 'la-5', name: 'Aprendizado', score: 78, color: '#EC4899' },
    { id: 'la-6', name: 'Clareza', score: 68, color: '#F59E0B' },
  ],
  risks: [
    { id: 'r-1', title: 'Runway < 3 meses se Solar não fechar', severity: 'high', category: 'Financeiro' },
    { id: 'r-2', title: 'Equipe Soul Krieg desmotivada', severity: 'medium', category: 'Pessoas' },
    { id: 'r-3', title: 'Burry perdendo janela de mercado', severity: 'low', category: 'Estratégia' },
  ],
  identityItems: identitySeedItems,
  identityChecks: identitySeedChecks,
  nextActions: [
    { id: 'na-1', text: 'Enviar proposta revisada — Solar Machine', done: false, project: 'Solar Machine' },
    { id: 'na-2', text: 'Contratar dev sênior para Soul Krieg', done: false, project: 'Soul Krieg' },
    { id: 'na-3', text: 'Definir pricing 21GO v2', done: false, project: '21GO' },
    { id: 'na-4', text: 'Revisar OKRs do trimestre', done: true },
  ],
  weekSummary: 'Semana produtiva. Solar Machine avançou nas negociações. Soul Krieg entregou MVP da fase 2. Foco na semana: fechar o contrato e garantir runway.',
  energyLevel: 78,
  focusLevel: 85,
  disciplineLevel: 70,
  clarityLevel: 82,
  version: '1.0',
};
